### ISSUE TITLE
Not working on Mikrotik x86

### ISSUE THREAD

**Issue by g2ufo** [beeyev/Mikrotik-RouterOS-automatic-backup-and-update#22]
Script not running on Mikrotik x86 .I think it is because /system routerboard command is empty on x86 (even no winbox menu). Or maybe somethong else...

After start in log view only the next line:

Bkp&Upd: script "Mikrotik RouterOS automatic backup & update" started.
Bkp&Upd: Script Mode: backup, forceBackup: false

**Comment by blindrain** [comment]
I Tried to remedy this issue  
by modifing lines 165-168  to : 
`:if ([/system/resource/get board-name]="x86") do={`
`:local deviceRbModel			[/system resource get architecture-name];`
`:local deviceRbSerialNumber 	[/system resource get board-name];`
`:local deviceRbCurrentFw 		[/system resource get version];`
`:local deviceRbUpgradeFw 		[/system resource get version];`
`} else={`
`:local deviceRbModel			[/system routerboard get model];`
`:local deviceRbSerialNumber 	[/system routerboard get serial-number];`
`:local deviceRbCurrentFw 		[/system routerboard get current-firmware];`
`:local deviceRbUpgradeFw 		[/system routerboard get upgrade-firmware];`
`};
`
Seems to correct it if you don't modify anything else. 

Where I tried to Change Variable `scriptMode` on line 31 along with the fix above. 
to be something along the lines. of
`:if ([/system clock get date]~"/08/") do={`
`#place instructions here`
`:local scriptMode "osupdate";`
`} else={`
`#place instructions here`
`:local scriptMode "osnotify";`
`};`
So that it  only updates the patch version on the 8th day of the month. it fails at 


[blindrain@Travis New] /system/resource> /system script/run BackupAndUpdate 
syntax error (line 232 column 21)   Which is line 221  on the existing script.   I have a different modification that changes the line numbers. 
`		:set scriptMode "backup";`

More Details: 
Here is the rest of my variables:   and this is on ROS v. 7.1.1 x86
```
## Additional parameter if you set `scriptMode` to `osupdate` or `osnotify`
# Set `true` if you want the script to perform backup every time it's fired, whatever script mode is set.
:local forceBackup true;
## Backup encryption password, no encryption if no password.
:local backupPassword "****************"
## If true, passwords will be included in exported config.
:local sensetiveDataInConfig true;
## Update channel. Possible values: stable, long-term, testing, development
:local updateChannel "stable";
## Install only patch versions of RouterOS updates.
## Works only if you set scriptMode to "osupdate"
## Means that new update will be installed only if MAJOR and MINOR version numbers remained the same as currently installed RouterOS.
## Example: v6.43.6 => major.minor.PATCH
## Script will send information if new version is greater than just patch.
:local installOnlyPatchUpdates	true;

```

**Comment by adval40** [comment]
I have the same issue    OS 7.1.3 and 7.1.2
your script works  on rb4011 /rb3011 /rb2011 
but i have the same email error  on a crs112  or RB952Ui
i can't find the solution 
thanks in advance  

ad adval40    adval40@gmail.com

**Comment by beeyev** [comment]
@adval40 Make sure that `Identity` (custom device name) on these devices does not contain any spaces or special characters.

**Comment by adval40** [comment]
i use as identity   "test"    

on crs112  works it's now 
but on the  rb952    it's not working 

thanks in advance

**Comment by akha666** [comment]
Does any one got the solution for this issue?
I have tried the script with VM. 
Mikrotik VM x86 >> not works.
Mikrotik VM x86_64 >> works.

**Comment by beeyev** [comment]
Could you try to run the script manually and show logs with an error?
Run this command in console:
```
/system script run BackupAndUpdate;
```

**Comment by akha666** [comment]
same here when run it manually.
![BBISvkO](https://user-images.githubusercontent.com/28590461/177225070-57d3592f-bcd4-464d-8085-034ed4c6d085.png)

**Comment by beeyev** [comment]
I am trying to find this bug, to make it easier I need your help. Could someone who experience this problem export router's configuration and share it with me?
Use this command:
```
/export compact hide-sensitive terse file=backup.txt;
```
It will generate a new backup. You can send it to my email alexander.tebiev@gmail.com

**Comment by akha666** [comment]
> I am trying to find this bug, to make it easier I need your help. Could someone who experience this problem export router's configuration and share it with me? Use this command:
> 
> ```
> /export compact hide-sensitive terse file=backup.txt;
> ```
> 
> It will generate a new backup. You can send it to my email [alexander.tebiev@gmail.com](mailto:alexander.tebiev@gmail.com)

The backup has been sent . Kindly check your mail with subject "**Mikrotik backup requested for x86 issue**". 
This backup from the MT fresh installed. No rules or firewall setting, only WAN enabled with DHCP client for internet access

**Comment by beeyev** [comment]
Hello guys,
Here is a [fixed version](https://raw.githubusercontent.com/beeyev/Mikrotik-RouterOS-automatic-backup-and-update/81799715db782c5712702adc54333f818fa47844/BackupAndUpdate.rsc). Could someone check it?

**Comment by weitgmbh** [comment]
Many thanks, @beeyev.
The script works fine on both routers that have failed previously.

**Comment by beeyev** [comment]
Great, I will merge the changes and close the issue then.

**Comment by albandes** [comment]
It's working OK, thank you very much!!
